### ISSUE TITLE
Honcho Start Error

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/sams#39]
Any thoughts on why I may be getting this error when starting sams with Honcho? Thanks 

`root@id15904:/opt/sams/src/server# honcho start
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
21:48:23 system        | api.1 started (pid=6321)
21:48:23 api.1         | /bin/sh: gunicorn: command not found
21:48:23 system        | api.1 stopped (rc=127)
21:48:23 system        | file_server.1 started (pid=6322)
21:48:23 system        | sending SIGTERM to file_server.1 (pid 6322)
21:48:23 file_server.1 | /bin/sh: gunicorn: command not found
21:48:23 system        | file_server.1 stopped (rc=-15)
`

**Comment by MarkLark86** [comment]
Hi @Aaronjacobs678 It looks like `gunicorn` is not installed:
```sh
21:48:23 system | api.1 started (pid=6321)
21:48:23 api.1 | /bin/sh: gunicorn: command not found
21:48:23 system | api.1 stopped (rc=127)
21:48:23 system | file_server.1 started (pid=6322)
21:48:23 system | sending SIGTERM to file_server.1 (pid 6322)
21:48:23 file_server.1 | /bin/sh: gunicorn: command not found
21:48:23 system | file_server.1 stopped (rc=-15)
```

The output here states `/bin/sh: gunicorn: command not found`
Please install `gunicorn` and try again

**Comment by Aaronjacobs678** [comment]
How silly of me - I should have spotted this! So quickly installed the gunicorn module and now I am experienced this error, which I have sat over for an hour and cannot seem to debug. Any thoughts @MarkLark86 ? 

`root@id15904:/opt/sams/src/server# honcho start
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=                                                                                                                                                             1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=                                                                                                                                                             1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
22:12:21 system        | api.1 started (pid=1406)
22:12:21 system        | file_server.1 started (pid=1407)
22:12:21 api.1         | [2021-07-04 22:12:21 +0000] [1406] [INFO] Starting guni                                                                                                                                                             corn 20.1.0
22:12:21 file_server.1 | [2021-07-04 22:12:21 +0000] [1407] [INFO] Starting guni                                                                                                                                                             corn 20.1.0
22:12:21 api.1         | [2021-07-04 22:12:21 +0000] [1406] [INFO] Listening at:                                                                                                                                                              http://0.0.0.0:5700 (1406)
22:12:21 api.1         | [2021-07-04 22:12:21 +0000] [1406] [INFO] Using worker:                                                                                                                                                              sync
22:12:21 file_server.1 | [2021-07-04 22:12:21 +0000] [1407] [INFO] Listening at:                                                                                                                                                              http://0.0.0.0:5750 (1407)
22:12:21 file_server.1 | [2021-07-04 22:12:21 +0000] [1407] [INFO] Using worker:                                                                                                                                                              sync
22:12:21 api.1         | [2021-07-04 22:12:21 +0000] [1413] [INFO] Booting worke                                                                                                                                                             r with pid: 1413
22:12:21 file_server.1 | [2021-07-04 22:12:21 +0000] [1414] [INFO] Booting worke                                                                                                                                                             r with pid: 1414
22:12:21 api.1         | [2021-07-04 22:12:21 +0000] [1417] [INFO] Booting worke                                                                                                                                                             r with pid: 1417
22:12:21 file_server.1 | [2021-07-04 22:12:21 +0000] [1418] [INFO] Booting worke                                                                                                                                                             r with pid: 1418
22:12:21 api.1         | [2021-07-04 22:12:21 +0000] [1419] [INFO] Booting worke                                                                                                                                                             r with pid: 1419
22:12:21 file_server.1 | [2021-07-04 22:12:21 +0000] [1420] [INFO] Booting worke                                                                                                                                                             r with pid: 1420
22:12:25 api.1         | 2021-07-04 22:12:25,858 level=DEBUG pid=1417 function=sams:logger:configure_logging Logging configured
22:12:25 file_server.1 | 2021-07-04 22:12:25,871 level=DEBUG pid=1414 function=sams:logger:configure_logging Logging configured
22:12:25 api.1         | 2021-07-04 22:12:25,893 level=DEBUG pid=1413 function=sams:logger:configure_logging Logging configured
22:12:25 api.1         | 2021-07-04 22:12:25,907 level=DEBUG pid=1419 function=sams:logger:configure_logging Logging configured
22:12:25 file_server.1 | 2021-07-04 22:12:25,910 level=DEBUG pid=1418 function=sams:logger:configure_logging Logging configured
22:12:25 file_server.1 | 2021-07-04 22:12:25,920 level=DEBUG pid=1420 function=sams:logger:configure_logging Logging configured
22:12:26 file_server.1 | [2021-07-04 22:12:26 +0000] [1407] [WARNING] Worker with pid 1420 was terminated due to signal 15
22:12:26 file_server.1 | [2021-07-04 22:12:26 +0000] [1407] [WARNING] Worker with pid 1418 was terminated due to signal 15
22:12:26 api.1         | [2021-07-04 22:12:26 +0000] [1406] [WARNING] Worker with pid 1419 was terminated due to signal 15
22:12:26 file_server.1 | [2021-07-04 22:12:26 +0000] [1407] [INFO] Shutting down: Master
22:12:26 file_server.1 | [2021-07-04 22:12:26 +0000] [1407] [INFO] Reason: Worker failed to boot.
22:12:26 system        | file_server.1 stopped (rc=3)
22:12:26 system        | sending SIGTERM to api.1 (pid 1406)
22:12:27 api.1         | Traceback (most recent call last):
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 209, in run
22:12:27 api.1         |     self.sleep()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 357, in sleep
22:12:27 api.1         |     ready = select.select([self.PIPE[0]], [], [], 1.0)
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
22:12:27 api.1         |     self.reap_workers()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
22:12:27 api.1         |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
22:12:27 api.1         | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
22:12:27 api.1         |
22:12:27 api.1         | During handling of the above exception, another exception occurred:
22:12:27 api.1         |
22:12:27 api.1         | Traceback (most recent call last):
22:12:27 api.1         |   File "/usr/local/bin/gunicorn", line 8, in <module>
22:12:27 api.1         |     sys.exit(run())
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
22:12:27 api.1         |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 231, in run
22:12:27 api.1         |     super().run()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 72, in run
22:12:27 api.1         |     Arbiter(self).run()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 229, in run
22:12:27 api.1         |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 342, in halt
22:12:27 api.1         |     self.stop()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 393, in stop
22:12:27 api.1         |     time.sleep(0.1)
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
22:12:27 api.1         |     self.reap_workers()
22:12:27 api.1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
22:12:27 api.1         |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
22:12:27 api.1         | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
22:12:27 system        | api.1 stopped (rc=1)
`

**Comment by MarkLark86** [comment]
@Aaronjacobs678
This application does not run as a daemon, meaning when you start the API using honcho, the app will continue to run in the terminal on which you started it, waiting for API requests to be processed (in the same way Superdesk APIs are run)

**Comment by Aaronjacobs678** [comment]
@MarkLark86 - Right, I see! Thank you kindly for all the information you have provided! I am still fairly new to the world of Ubuntu / Linux. Trying to get all this setup has given me a few grey hairs, but I hope I am getting closer! 

Thanks again :-)

**Comment by MarkLark86** [comment]
My pleasure, enjoy
