### ISSUE TITLE
SAMS Details

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/sams#40]
Good afternoon - My apologies that this is not the appropriate method of contact for this question. 

Could somebody just inform me what SAMS is actually for? I am trying to use AWS S3 to store all of the Superdesk images / assets and am under the impression that then our journalists can then 'get' and 'insert' items from S3 back into their written content on Superdesk. I have setup SAMS, but am unsure how to 'get' items back into Superdesk from S3. Is this what SAMS was built for, or have I got my wires twisted?

Many thanks for your great help so far!

**Comment by MarkLark86** [comment]
Hi @Aaronjacobs678 

SAMS is an Asset Management System, with the ability to store Assets in multiple different destinations (currently supported: AWS S3, Mongo GridFS).

All Assets must be managed (created, updated and deleted) through SAMS, as SAMS contains metadata and actions that are not available across all storage destination types. We do not have a mechanism to import, or synchronise, existing Assets from S3 into SAMS.

There are two ways to manage these Assets:
* Using the Python client library (provided via `pip install sams-client`)
* Using Superdesk SAMS Workspace (a UI to manage Assets in SAMS)

**Superdesk SAMS Workspace:**
![image](https://user-images.githubusercontent.com/22425232/125740953-1e2a452b-de6f-423e-9f9f-c4cbad9a7e75.png)


Besides the aforementioned Superdesk UI, the only other integration we have with Superdesk and SAMS is with the Attachments to a news item.

**Superdesk Attachments widget**
![image](https://user-images.githubusercontent.com/22425232/125741057-9fb991b9-aee3-475f-ac0e-c762abf04973.png)

All other images / Assets are stored using Superdesk's storage mechanism (in the same way as if SAMS was not used at all).

**Comment by Aaronjacobs678** [comment]
@MarkLark86 - this is absoloutely fantastic! Thank you so much for all the detail that was put into this. Maybe it could be added to the ReadTheDocs as an introduction? 

I have managed to get the server up and running, but am still attempting to figure out how to actually get it to show / create the SAMS UI in Superdesk. Is there any other instructional material?
Thanks

**Comment by Aaronjacobs678** [comment]
@MarkLark86 - this is absoloutely fantastic! Thank you so much for all the detail that was put into this. Maybe it could be added to the ReadTheDocs as an introduction? 

I have managed to get the server up and running, but am still attempting to figure out how to actually get it to show / create the SAMS UI in Superdesk. Is there any other instructional material?
Thanks

**Comment by MarkLark86** [comment]
@Aaronjacobs678
SAMS is actually an independent service from Superdesk. It does not require Superdesk at all to run. That is why the docs for SAMS does not include Superdesk specifics.

In saying that, we will add documentation in the Superdesk ReadTheDocs on how to enable SAMS integration into Superdesk.

In the meantime, we have a branch set up already with this integration enabled: https://github.com/superdesk/superdesk/tree/sams

Have a look at the server's settings/Procfile, and client's package.json/index files. I believe that should give you an idea of what is required

**Comment by Aaronjacobs678** [comment]
I see! Will appreciate the documentation. I am trying to compare the two branches and have copied over some setting. Do you have any thought to why I am experiencing this problem?

`Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 | [2021-07-16 14:52:30 +0000] [8093] [ERROR] Exception in worker process
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 | Traceback (most recent call last):
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     worker.init_process()
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     self.load_wsgi()
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     self.wsgi = self.app.wsgi()
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     self.callable = self.load()
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     return self.load_wsgiapp()
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     return util.import_app(self.app_uri)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     mod = importlib.import_module(module)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     return _bootstrap._gcd_import(name[level:], package, level)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/server/wsgi.py", line 14, in <module>
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     application = get_app()
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/server/app.py", line 33, in get_app
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     app = superdesk_app(config)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/src/superdesk-core/superdesk/factory/app.py", line 236, in get_app
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     install_app(module_name)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/src/superdesk-core/superdesk/factory/app.py", line 228, in install_app
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     app_module = importlib.import_module(module_name)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     return _bootstrap._gcd_import(name[level:], package, level)
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/src/superdesk-core/superdesk/sams/__init__.py", line 3, in <module>
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     from .assets import assets_bp, unlock_asset_by_user
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/src/superdesk-core/superdesk/sams/assets.py", line 29, in <module>
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     from .utils import get_file_from_sams
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |   File "/opt/superdesk/env/src/superdesk-core/superdesk/sams/utils.py", line 20, in <module>
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 |     from sams_client import SamsClient
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 | ModuleNotFoundError: No module named 'sams_client'
Jul 16 14:52:30 id15904.example.com sh[8052]: 14:52:30 rest.1 | [2021-07-16 14:52:30 +0000] [8093] [INFO] Worker exiting (pid: 8093)
`

**Comment by Aaronjacobs678** [comment]
Have tried multiple installs with always a failure in the Supedesk Log with "sams_client not found". Any thoughts?

**Comment by MarkLark86** [comment]
If you're using the latest code from `develop` branches in `superdesk-core`, we have another branch set up for this also:
https://github.com/superdesk/superdesk/tree/sams-develop

Try using the settings/Procfile, package.json/index files from them (you may also want to have a look at `server/requirements.txt` from these branches)

**Comment by Aaronjacobs678** [comment]
@MarkLark86 - thanks. I am still getting the above error, where it is unable to find the sams_client. What is looking for this? Where should I be looking to find a resoloution? 

Thanks

**Comment by MarkLark86** [comment]
@Aaronjacobs678 
The error you're experiencing is coming from a SAMS proxy that runs inside the Superdesk wsgi application (the Superdesk API).

Make sure `sams_client` is installed in the same python virtual environment that Superdesk runs from.

**Comment by Aaronjacobs678** [comment]
Looks like it!

```
root@id15904:~# pip install sams-client
Requirement already satisfied: sams-client in /opt/superdesk/server/src/sams-cli                                                                                                                                                         ent/src/clients/python (0.2.3)
Requirement already satisfied: requests<3.0,>=2.7.0 in /usr/lib/python3/dist-pac                                                                                                                                                             kages (from sams-client) (2.22.0)
root@id15904:~#

```

**Comment by Aaronjacobs678** [comment]
@MarkLark86 - Is there anything you do not know?! Solved. PIP-Install did not install into the correct directory, and was also (weirdly) installing an older version of SAMS. Kindest thanks for all your support - I have logged all my actions encase they become useful for anybody in the future. Such a great community here! Thanks again pal!
