### ISSUE TITLE
Question - Thumbnails

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/sams#42]
Good Afternoon!

Is there a way to view thumbnails when viewing media items within Superdesk SAMS? Instead of seeing the grey box and camera icon...

Thanks

**Comment by MarkLark86** [comment]
Hi @Aaronjacobs678,

SAMS (and the Superdesk SAMS Workspace) is still in the early stages of development.

This feature will be added at some point, though a time frame for this is not currently available.

**Comment by MarkLark86** [comment]
Hi @Aaronjacobs678,

Thumbnails inside the SAMS Workspace UI has now been achieved. The following are the branch/version required for this:
* superdesk-core: develop branch from github
* superdesk-client-core: develop branch from github
* sams-server: 0.3.1 (from pypi), or develop branch from github
* sams-client: 0.3.1 (from pypi), or develop branch from github

**Comment by Aaronjacobs678** [comment]
Thats Awesome!
Thanks
