### ISSUE TITLE
Question - Using a SAMS Asset as Featured Image

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/sams#43]
Good Afternoon! 

Ofcourse I can attach a SAMS asset to an article with great ease! However, how do I quickly use a SAMS Asset as a 'Featured Image'. It appears at the moment I would have to download the asset to my computer, then re-upload to the article.

Is there a way round this? Or is it a planned feature...

Thanks

**Comment by MarkLark86** [comment]
Hi @Aaronjacobs678,
Unfortunately this feature is not currently available.

It is our desire to integrate SAMS into more places of the authoring workflow, though a time frame for this is not currently available.
